name: Release
on:
  release:
    types: [published]

jobs:
  release:
    name: Release Plugin
    uses: KatsuteTF/Workflows/.github/workflows/release.yml@main
    with:
      file: Upgrades.sp
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}